name: Build Gradle project

on:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.14.0-dev.1320+492cc2ef8'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build
        run: |
          ./gradlew assemble

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: build/libs/
          if-no-files-found: error

  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-latest, macos-13, macos-latest, windows-2019, windows-latest, alpine ]
        include:
            - os: alpine
              container: openjdk:17-alpine
      fail-fast: false
    runs-on: ${{ matrix.os == 'alpine' && 'ubuntu-latest' || matrix.os }}
    container: ${{ matrix.container }}

    needs: build

    steps:
      # Without installing Git here the checkout has no .git directory on Alpine
      - name: Install dependencies
        if: matrix.os == 'alpine'
        run: |
          apk update
          apk add --no-cache git udev

      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Without this the directory is not marked as safe on Alpine
      - if: matrix.os == 'alpine'
        name: Mark as safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up JDK
        if: matrix.os != 'alpine'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Download library
        uses: actions/download-artifact@v4
        with:
          name: library
          path: build/remote/

      - name: Test
        run: |
          ./gradlew externalTest

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.os }}
          path: build/reports/
