name: Build Gradle project

on:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.13.0'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          ./gradlew build
